package transform

import (
	"fmt"
	"go/format"
	"go/types"
	"sort"
	"strings"
	"unicode"
)

// bridgePkgPath is the import path of the public generated-bridge ABI package.
const bridgePkgPath = "github.com/Voskan/BatchWeaver/bridge"

// bridgeReq describes a runtime bridge to generate for one operation in one
// package. Multiple lowered call sites in the same package share one bridge.
type bridgeReq struct {
	pkgDir     string // workspace-relative directory of the package
	pkgName    string // Go package name for the clause
	op         string // operation ID
	varName    string // generated bridge variable name
	recvType   string // rendered receiver type
	keyType    string // rendered key type
	valueType  string // rendered value type
	scalarName string // scalar method name
	file       string // workspace-relative bridge file path
	imports    map[string]string
}

// importCollector records the packages referenced while rendering types so the
// generated file can import exactly what it uses. Types in the local package
// render unqualified and are not imported.
type importCollector struct {
	pkgs  map[string]string
	local *types.Package
}

func newImportCollector() *importCollector { return &importCollector{pkgs: map[string]string{}} }

func (ic *importCollector) qualify(p *types.Package) string {
	if p == nil || p == ic.local {
		return ""
	}
	ic.pkgs[p.Path()] = p.Name()
	return p.Name()
}

// render renders a type to source, recording its package imports.
func (ic *importCollector) render(t types.Type) string {
	return types.TypeString(t, ic.qualify)
}

// generateBridge renders the deterministic bridge file content for a request.
func generateBridge(br *bridgeReq) ([]byte, error) {
	imports := map[string]string{"context": "context", bridgePkgPath: "bridge"}
	for path, name := range br.imports {
		imports[path] = name
	}
	// The bridge package name is fixed; do not let a type package named "bridge"
	// collide with it (rejected earlier by shape validation in practice).
	var b strings.Builder
	b.WriteString("// Code generated by BatchWeaver. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", br.pkgName)
	b.WriteString("import (\n")
	paths := make([]string, 0, len(imports))
	for p := range imports {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q\n", p)
	}
	b.WriteString(")\n\n")
	fmt.Fprintf(&b, "// %s lowers operation %s to the BatchWeaver runtime. It coalesces\n", br.varName, br.op)
	b.WriteString("// compatible calls through an active scope and otherwise calls the scalar\n")
	b.WriteString("// method directly.\n")
	fmt.Fprintf(&b, "var %s = bridge.Operation[%s, %s, %s]{\n", br.varName, br.recvType, br.keyType, br.valueType)
	fmt.Fprintf(&b, "\tOpID: %q,\n", br.op)
	fmt.Fprintf(&b, "\tScalar: func(ctx context.Context, r %s, k %s) (%s, error) {\n", br.recvType, br.keyType, br.valueType)
	fmt.Fprintf(&b, "\t\treturn r.%s(ctx, k)\n", br.scalarName)
	b.WriteString("\t},\n}\n")

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated bridge for %s: %w", br.op, err)
	}
	return formatted, nil
}

// bridgeVarName returns the deterministic bridge variable name for an operation.
func bridgeVarName(op string) string {
	var b strings.Builder
	b.WriteString("bwop")
	capNext := true
	for _, r := range op {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			capNext = true
			continue
		}
		if capNext {
			b.WriteRune(unicode.ToUpper(r))
			capNext = false
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

// bridgeFileName returns the deterministic bridge file base name for an operation.
func bridgeFileName(op string) string {
	var b strings.Builder
	for _, r := range op {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToLower(r))
		} else {
			b.WriteByte('_')
		}
	}
	return "zz_batchweaver_" + b.String() + "_gen.go"
}
