package transform

import (
	"context"
	"errors"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"

	"github.com/Voskan/BatchWeaver/internal/adapter"
)

// SQL transformation rejection codes. They remain in the BW35xx compiler
// transformation range and fail closed before an overlay is persisted.
const (
	CodeSQLTransformInput     = "BW3510"
	CodeSQLTransformPlan      = "BW3511"
	CodeSQLTransformTypecheck = "BW3512"
)

// ErrSQLTransformation marks a rejected SQL source-generation plan.
var ErrSQLTransformation = errors.New("SQL synthesis transformation rejected")

// SQLPlanRequest describes a generated, compile-checked Go binding for one
// validated SQL synthesis plan. Output is workspace-relative and must name a
// new .go file in the target package.
type SQLPlanRequest struct {
	Workspace   string
	PackageName string
	PackagePath string
	Output      string
	Constant    string
	Operation   string
	Synthesis   adapter.SynthPlan
}

// BuildSQLSynthesisPlan creates a content-addressed transformation plan whose
// generated Go file exposes the synthesized query and its integrity digest. It
// type-checks the new file in an in-memory overlay and does not write source.
func BuildSQLSynthesisPlan(ctx context.Context, req SQLPlanRequest) (*Plan, error) {
	if err := validateSQLPlanRequest(req); err != nil {
		return nil, err
	}
	if err := validateGeneratedTarget(req.Workspace, req.Output); err != nil {
		return nil, err
	}
	content, err := format.Source([]byte(fmt.Sprintf("// Code generated by BatchWeaver; DO NOT EDIT.\n\npackage %s\n\nconst %s = %s\nconst %sDigest = %s\n",
		req.PackageName, req.Constant, strconv.Quote(req.Synthesis.Query), req.Constant, strconv.Quote(req.Synthesis.Digest))))
	if err != nil {
		return nil, fmt.Errorf("%s: %w: format generated binding: %w", CodeSQLTransformInput, ErrSQLTransformation, err)
	}
	output := filepath.ToSlash(filepath.Clean(req.Output))
	if err := typeCheckSQLOverlay(ctx, req.Workspace, req.PackagePath, output, content); err != nil {
		return nil, fmt.Errorf("%s: %w: %w", CodeSQLTransformTypecheck, ErrSQLTransformation, err)
	}
	strategy := StrategyExactKeySQLSynthesis
	if len(req.Synthesis.KeyTypes) > 1 {
		strategy = StrategyCompositeKeySQLSynthesis
	}
	if req.Synthesis.JoinContract != "" {
		strategy = StrategyBoundedJoinSQLSynthesis
	}
	candidateID := shortID("bwsqlcandidate", req.Operation, req.Synthesis.Digest)
	certificateID := shortID("bwsqlproof", req.Synthesis.Digest)
	tr := Transformation{
		CandidateID: candidateID, CertificateID: certificateID, Strategy: strategy,
		Operation:        req.Operation,
		Source:           SourceAnchor{File: output, Package: req.PackagePath, StructuralHash: hashParts("sql", req.Synthesis.Digest)[:shortLen], Resolution: AnchorExact},
		Phases:           []Phase{PhaseBindInvariants, PhaseSynthesizeSQL, PhaseValidateGlobal, PhaseMapResults, PhaseFinalize},
		GeneratedSymbols: []string{req.Constant, req.Constant + "Digest"},
		NonGuarantees:    []string{"database uniqueness is not inferred; joined plans require the explicit at-most-one contract recorded in the synthesis digest"},
	}
	tr.ID = shortID("bwtransform", candidateID, certificateID, string(strategy))
	tr.Digest = hashParts(tr.ID, req.Synthesis.Digest, hashBytes(content), output)
	plan := &Plan{
		SchemaVersion: SchemaVersion, Workspace: req.Workspace,
		AnalysisDigest: req.Synthesis.Digest, ProofSchema: "batchweaver.sql-proof/v1alpha1",
		ContractDigest: req.Synthesis.Digest, StrategyVersion: StrategyVersion,
		Transformations: []Transformation{tr},
		Files:           []FilePlan{{Path: output, OriginalDigest: hashBytes(nil), TransformedDigest: hashBytes(content), Created: true, Generated: true, transformed: content}},
		Validation:      ValidationSummary{Parse: ValidationPassed, TypeCheck: ValidationPassed, Preconditions: ValidationPassed, Structural: ValidationPassed, Detail: "generated SQL binding type-checks in workspace overlay"},
	}
	finalizePlanDigest(plan)
	return plan, nil
}

func validateGeneratedTarget(root, output string) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("%s: %w: resolve workspace: %w", CodeSQLTransformInput, ErrSQLTransformation, err)
	}
	target := filepath.Join(absRoot, filepath.FromSlash(output))
	rel, err := filepath.Rel(absRoot, target)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("%s: %w: output escapes workspace", CodeSQLTransformInput, ErrSQLTransformation)
	}
	if _, err := os.Lstat(target); err == nil {
		return fmt.Errorf("%s: %w: output already exists: %s", CodeSQLTransformInput, ErrSQLTransformation, output)
	} else if !os.IsNotExist(err) {
		return fmt.Errorf("%s: %w: inspect output: %w", CodeSQLTransformInput, ErrSQLTransformation, err)
	}
	resolvedRoot, err := filepath.EvalSymlinks(absRoot)
	if err != nil {
		return fmt.Errorf("%s: %w: resolve workspace symlinks: %w", CodeSQLTransformInput, ErrSQLTransformation, err)
	}
	resolvedParent, err := filepath.EvalSymlinks(filepath.Dir(target))
	if err != nil {
		return fmt.Errorf("%s: %w: output parent must exist inside the workspace: %w", CodeSQLTransformInput, ErrSQLTransformation, err)
	}
	parentRel, err := filepath.Rel(resolvedRoot, resolvedParent)
	if err != nil || parentRel == ".." || strings.HasPrefix(parentRel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("%s: %w: output parent resolves outside workspace", CodeSQLTransformInput, ErrSQLTransformation)
	}
	return nil
}

func validateSQLPlanRequest(req SQLPlanRequest) error {
	if req.Workspace == "" || req.PackageName == "" || req.PackagePath == "" || req.Operation == "" || !token.IsIdentifier(req.PackageName) || !token.IsIdentifier(req.Constant) {
		return fmt.Errorf("%s: %w: workspace, package, operation, and Go constant identifier are required", CodeSQLTransformInput, ErrSQLTransformation)
	}
	output := filepath.ToSlash(filepath.Clean(req.Output))
	if output == "." || filepath.IsAbs(req.Output) || strings.HasPrefix(output, "../") || filepath.Ext(output) != ".go" {
		return fmt.Errorf("%s: %w: output must be a workspace-relative .go file", CodeSQLTransformInput, ErrSQLTransformation)
	}
	if err := req.Synthesis.Validate(); err != nil {
		return fmt.Errorf("%s: %w: %w", CodeSQLTransformPlan, ErrSQLTransformation, err)
	}
	return nil
}

func typeCheckSQLOverlay(ctx context.Context, root, packagePath, output string, content []byte) error {
	cfg := &packages.Config{
		Mode:    packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedDeps,
		Context: ctx, Dir: root,
		Overlay: map[string][]byte{filepath.Join(root, filepath.FromSlash(output)): content},
	}
	loaded, err := packages.Load(cfg, packagePath)
	if err != nil {
		return err
	}
	if len(loaded) == 0 {
		return fmt.Errorf("package %s was not found", packagePath)
	}
	var failures []string
	packages.Visit(loaded, nil, func(pkg *packages.Package) {
		for _, pkgErr := range pkg.Errors {
			failures = append(failures, pkgErr.Error())
		}
	})
	if len(failures) > 0 {
		return fmt.Errorf("%s", strings.Join(failures, "; "))
	}
	return nil
}

// VerifySQLSynthesisPlan rechecks a persisted SQL plan's content hashes,
// generated symbols, structural state, and canonical plan identity. SQL plans
// are generated from an explicit query rather than rediscovered Go call sites,
// so verification is self-contained and does not rerun general candidate analysis.
func VerifySQLSynthesisPlan(plan *Plan) error {
	if plan == nil || plan.ProofSchema != "batchweaver.sql-proof/v1alpha1" || len(plan.Transformations) != 1 || len(plan.Files) != 1 {
		return fmt.Errorf("%s: %w: not a SQL synthesis plan", CodeSQLTransformPlan, ErrSQLTransformation)
	}
	for _, file := range plan.Files {
		if !file.Created || !file.Generated || hashBytes(file.transformed) != file.TransformedDigest {
			return fmt.Errorf("%s: %w: generated file digest mismatch", CodeSQLTransformPlan, ErrSQLTransformation)
		}
	}
	tr, file := plan.Transformations[0], plan.Files[0]
	if tr.Strategy != StrategyExactKeySQLSynthesis && tr.Strategy != StrategyCompositeKeySQLSynthesis && tr.Strategy != StrategyBoundedJoinSQLSynthesis {
		return fmt.Errorf("%s: %w: unknown SQL synthesis strategy", CodeSQLTransformPlan, ErrSQLTransformation)
	}
	expectedCandidate := shortID("bwsqlcandidate", tr.Operation, plan.AnalysisDigest)
	expectedCertificate := shortID("bwsqlproof", plan.AnalysisDigest)
	expectedID := shortID("bwtransform", expectedCandidate, expectedCertificate, string(tr.Strategy))
	expectedDigest := hashParts(expectedID, plan.AnalysisDigest, file.TransformedDigest, file.Path)
	if tr.CandidateID != expectedCandidate || tr.CertificateID != expectedCertificate || tr.ID != expectedID || tr.Digest != expectedDigest || tr.Source.File != file.Path {
		return fmt.Errorf("%s: %w: transformation identity mismatch", CodeSQLTransformPlan, ErrSQLTransformation)
	}
	if structuralOK(plan) != ValidationPassed || len(BuildSourceMap(plan).Segments) != 1 {
		return fmt.Errorf("%s: %w: generated SQL binding structure mismatch", CodeSQLTransformPlan, ErrSQLTransformation)
	}
	wantID, wantDigest := plan.ID, plan.Digest
	copyPlan := *plan
	copyPlan.Transformations = append([]Transformation(nil), plan.Transformations...)
	copyPlan.Files = append([]FilePlan(nil), plan.Files...)
	finalizePlanDigest(&copyPlan)
	if copyPlan.ID != wantID || copyPlan.Digest != wantDigest {
		return fmt.Errorf("%s: %w: canonical plan digest mismatch", CodeSQLTransformPlan, ErrSQLTransformation)
	}
	return nil
}
